class PopulateBosses < ActiveRecord::Migration
  def up
  	Boss.create(:name => "The Prophet Skeram", :raid_id => '1')
  	Boss.create(:name => "Silithid Royalty", :raid_id => '1')
  	Boss.create(:name => "Battleguard Sartura", :raid_id => '1')
  	Boss.create(:name => "Fankriss the Unyielding", :raid_id => '1')
  	Boss.create(:name => "Viscidus", :raid_id => '1')
  	Boss.create(:name => "Princess Huhuran", :raid_id => '1')
  	Boss.create(:name => "Twin Emperors", :raid_id => '1')
  	Boss.create(:name => "Ouro", :raid_id => '1')
  	Boss.create(:name => "C'Thun", :raid_id => '1')
  	Boss.create(:name => "Razorgore the Untamed", :raid_id => '2')
  	Boss.create(:name => "Vaelastrasz the Corrupt", :raid_id => '2')
  	Boss.create(:name => "Broodlord Lashlayer", :raid_id => '2')
  	Boss.create(:name => "Firemaw", :raid_id => '2')
  	Boss.create(:name => "Ebonroc", :raid_id => '2')
  	Boss.create(:name => "Flamegor", :raid_id => '2')
  	Boss.create(:name => "Chromaggus", :raid_id => '2')
  	Boss.create(:name => "Nefarian", :raid_id => '2')
  	Boss.create(:name => "Lucifron", :raid_id => '3')
  	Boss.create(:name => "Magmadar", :raid_id => '3')
  	Boss.create(:name => "Gehennas", :raid_id => '3')
  	Boss.create(:name => "Garr", :raid_id => '3')
  	Boss.create(:name => "Shazzrah", :raid_id => '3')
  	Boss.create(:name => "Baron Geddon", :raid_id => '3')
  	Boss.create(:name => "Sulfuron Harbinger", :raid_id => '3')
  	Boss.create(:name => "Golemagg the Incinerator", :raid_id => '3')
  	Boss.create(:name => "Majordomo Executus", :raid_id => '3')
  	Boss.create(:name => "Ragnaros", :raid_id => '3')
  	Boss.create(:name => "Kurinnaxx", :raid_id => '4')
  	Boss.create(:name => "General Rajaxx", :raid_id => '4')
  	Boss.create(:name => "Moam", :raid_id => '4')
  	Boss.create(:name => "Buru the Gorger", :raid_id => '4')
  	Boss.create(:name => "Ayamiss the Hunter", :raid_id => '4')
  	Boss.create(:name => "Ossirian the Unscarred", :raid_id => '4')
  	Boss.create(:name => "High Warlord Naj'entus", :raid_id => '5')
  	Boss.create(:name => "Supremus", :raid_id => '5')
  	Boss.create(:name => "Shade of Akama", :raid_id => '5')
  	Boss.create(:name => "Teron Gorefiend", :raid_id => '5')
  	Boss.create(:name => "Gurtogg Bloodboil", :raid_id => '5')
  	Boss.create(:name => "Reliquary of Souls", :raid_id => '5')
  	Boss.create(:name => "Mother Shahraz", :raid_id => '5')
  	Boss.create(:name => "The Illidari Council", :raid_id => '5')
  	Boss.create(:name => "Illidan Stormrage", :raid_id => '5')
  	Boss.create(:name => "High King Maulgar", :raid_id => '6')
  	Boss.create(:name => "Gruul the Dragonkiller", :raid_id => '6')
  	Boss.create(:name => "Attumen the Huntsman", :raid_id => '7')
  	Boss.create(:name => "Moroes", :raid_id => '7')
  	Boss.create(:name => "Maiden of Virtue", :raid_id => '7')
  	Boss.create(:name => "Opera Event", :raid_id => '7')
  	Boss.create(:name => "The Curator", :raid_id => '7')
  	Boss.create(:name => "Chess Event", :raid_id => '7')
  	Boss.create(:name => "Terestian Illhoof", :raid_id => '7')
  	Boss.create(:name => "Shade of Aran", :raid_id => '7')
  	Boss.create(:name => "Netherspite", :raid_id => '7')
  	Boss.create(:name => "Prince Malchezaar", :raid_id => '7')
  	Boss.create(:name => "Nightbane", :raid_id => '7')
  	Boss.create(:name => "Magtheridon", :raid_id => '8')
  	Boss.create(:name => "Hydross the Unstable", :raid_id => '9')
  	Boss.create(:name => "The Lurker Below", :raid_id => '9')
  	Boss.create(:name => "Leotheras the Blind", :raid_id => '9')
  	Boss.create(:name => "Fathom-Lord Karathress", :raid_id => '9')
  	Boss.create(:name => "Morogrim Tidewalker", :raid_id => '9')
  	Boss.create(:name => "Lady Vashj", :raid_id => '9')
  	Boss.create(:name => "Al'ar", :raid_id => '10')
  	Boss.create(:name => "Void Reaver", :raid_id => '10')
  	Boss.create(:name => "High Astromancer Solarian", :raid_id => '10')
  	Boss.create(:name => "Kael'thas Sunstrider", :raid_id => '10')
  	Boss.create(:name => "Rage Winterchill", :raid_id => '11')
  	Boss.create(:name => "Anetheron", :raid_id => '11')
  	Boss.create(:name => "Kaz'rogal", :raid_id => '11')
  	Boss.create(:name => "Azgalor", :raid_id => '11')
  	Boss.create(:name => "Archimonde", :raid_id => '11')
  	Boss.create(:name => "Kalecgos", :raid_id => '12')
  	Boss.create(:name => "Brutallus", :raid_id => '12')
  	Boss.create(:name => "Felmyst", :raid_id => '12')
  	Boss.create(:name => "Eredar Twins", :raid_id => '12')
  	Boss.create(:name => "M'uru", :raid_id => '12')
  	Boss.create(:name => "Kil'jaeden", :raid_id => '12')
  	Boss.create(:name => "Imperial Vizier Zor'lok", :raid_id => '28')
  	Boss.create(:name => "Blade Lord Ta'yak", :raid_id => '28')
  	Boss.create(:name => "Garalon", :raid_id => '28')
  	Boss.create(:name => "Wind Lord Mel'jarak", :raid_id => '28')
  	Boss.create(:name => "Amber-Shaper Un'sok", :raid_id => '28')
  	Boss.create(:name => "Grand Empress Shek'zeer", :raid_id => '28')
  	Boss.create(:name => "The Stone Guard", :raid_id => '29')
  	Boss.create(:name => "Feng the Accursed", :raid_id => '29')
  	Boss.create(:name => "Gara'jal the Spiritbinder", :raid_id => '29')
  	Boss.create(:name => "The Spirit Kings", :raid_id => '29')
  	Boss.create(:name => "Elegon", :raid_id => '29')
  	Boss.create(:name => "Will of the Emperor", :raid_id => '29')
  	Boss.create(:name => "Protectors of the Endless", :raid_id => '30')
  	Boss.create(:name => "Tsulong", :raid_id => '30')
  	Boss.create(:name => "Lei Shi", :raid_id => '30')
  	Boss.create(:name => "Sha of Fear", :raid_id => '30')
  	Boss.create(:name => "Jin'rokh the Breaker", :raid_id => '31')
  	Boss.create(:name => "Horridon", :raid_id => '31')
  	Boss.create(:name => "Council of Elders", :raid_id => '31')
  	Boss.create(:name => "Tortos", :raid_id => '31')
  	Boss.create(:name => "Megaera", :raid_id => '31')
  	Boss.create(:name => "Ji-kun", :raid_id => '31')
  	Boss.create(:name => "Durumu", :raid_id => '31')
  	Boss.create(:name => "Primordius", :raid_id => '31')
  	Boss.create(:name => "Dark Animus", :raid_id => '31')
  	Boss.create(:name => "Iron Qon", :raid_id => '31')
  	Boss.create(:name => "Twin Consorts", :raid_id => '31')
  	Boss.create(:name => "Lei Shen", :raid_id => '31')
  	Boss.create(:name => "Ra-den", :raid_id => '31')
  end

  def down
  end
end
